### ISSUE TITLE
Compare-PSObject reports NotEqual for 2 arrays having the same items, but in a different order

### ISSUE THREAD

**Issue by JonathanPuvilland** [wethreetrees/PSObjectTools#6]
Great function, I love it, but I'd have expected that the comparisson of two arrays would report them a being equal is they contain the same items, irrespective of the order of the items. See for example below the `users` property where user1 and user2 are swapped.

```
PS  > $ReferenceObject                                                            
name  description            users          group
----  -----------            -----          -----
name1 Description for name1. {user1, user2} @{name=Group; owner=Owner}

PS > $DifferenceObject                                                           
name  description            users          group
----  -----------            -----          -----
name1 Description for name1. {user2, user1} @{owner=Owner; name=Group}

PS > Compare-PSObject -ReferenceObject $ReferenceObject -DifferenceObject $DifferenceObject -IncludeEqual
Property       ReferenceValue         DifferenceValue        Indicator
--------       --------------         ---------------        ---------
$_.description Description for name1. Description for name1. Equal
$_.group.name  Group                  Group                  Equal
$_.group.owner Owner                  Owner                  Equal
$_.name        name1                  name1                  Equal
$_.users[0]    user1                  user2                  NotEqual
$_.users[1]    user2                  user1                  NotEqual
```
Please note however that for a nested object (property `group` in the example), the order or the nested object's properties is not taken into account during the compare (`group.name` and `group.owner` are swapped and are considered equal)

**Comment by wethreetrees** [comment]
The array order being reported is expected, since the objects are different. When we are comparing objects, the goal is that for every `Property` we will get the same result on each object, and if not, it is reported as `NotEqual`.

I will open an enhancement for a parameter to loosely check arrays.

I would expect nested objects to follow the same logic though. Good catch!

I'll take a look!

**Comment by wethreetrees** [comment]
@JonathanPuvilland This should be resolved!
